import { LegalSection, LegalType } from '../database/entities';

// Built-in initial content, seeded as version 1 per type on first boot.
export const LEGAL_DEFAULTS: Record<LegalType, LegalSection[]> = {
  requirements: [
    { titleEs: 'Ser mayor de 18 años', titleEn: 'Be 18 or older', bodyEs: 'Debes tener al menos 18 años cumplidos para conducir con PasarEx.', bodyEn: 'You must be at least 18 years old to drive with PasarEx.' },
    { titleEs: 'Licencia de conducción vigente', titleEn: 'Valid driver’s licence', bodyEs: 'Licencia de conducción de Barbados vigente para la categoría de tu vehículo.', bodyEn: 'A current Barbados driver’s licence for your vehicle category.' },
    { titleEs: 'Vehículo elegible con documentos al día', titleEn: 'Eligible vehicle with current documents', bodyEs: 'Moto, carro, van o camioneta propios, con seguro obligatorio y registro vigentes.', bodyEn: 'Your own motorcycle, car, van or pickup, with valid compulsory insurance and registration.' },
    { titleEs: 'Smartphone compatible', titleEn: 'Compatible smartphone', bodyEs: 'iPhone o Android con plan de datos y GPS para recibir y rastrear entregas.', bodyEn: 'iPhone or Android with a data plan and GPS to receive and track deliveries.' },
    { titleEs: 'Documento de identidad', titleEn: 'Government-issued ID', bodyEs: 'Documento nacional de identidad de Barbados vigente para verificar tu identidad.', bodyEn: 'A valid Barbados national ID to verify your identity.' },
    { titleEs: 'Verificación de antecedentes', titleEn: 'Background check', bodyEs: 'Autorizas y debes aprobar la revisión de seguridad y antecedentes.', bodyEn: 'You authorize and must pass a security & background check.' },
    { titleEs: 'Cuenta bancaria a tu nombre', titleEn: 'Bank account in your name', bodyEs: 'Para recibir tus pagos por depósito directo.', bodyEn: 'To receive your earnings via direct deposit.' },
  ],
  terms: [
    { titleEs: '1. Aceptación y elegibilidad', titleEn: '1. Acceptance & eligibility', bodyEs: 'Al marcar la casilla de aceptación declaras que cumples todos los requisitos indicados y aceptas estos Términos de Servicio como condición para postularte y operar en la plataforma PasarEx LM.', bodyEn: 'By checking the acceptance box you represent that you meet all the requirements listed above and agree to these Terms of Service as a condition to apply for and operate on the PasarEx LM platform.' },
    { titleEs: '2. Contratista independiente', titleEn: '2. Independent contractor', bodyEs: 'Operas como contratista independiente. Estos Términos no crean una relación laboral, de agencia ni de sociedad. Eres responsable de tus impuestos y obligaciones de seguridad social.', bodyEn: 'You operate as an independent contractor. These Terms create no employment, agency or partnership relationship. You are responsible for your own taxes and social-security obligations.' },
    { titleEs: '3. Verificación de antecedentes y seguridad', titleEn: '3. Background & security verification', bodyEs: 'Autorizas a PasarEx LM y a sus aliados a verificar tu identidad, antecedentes y documentos. Aprobar la etapa de seguridad es obligatorio antes de recibir entregas.', bodyEn: 'You authorize PasarEx LM and its partners to verify your identity, background and documents. Passing the security stage is mandatory before you can receive deliveries.' },
    { titleEs: '4. Veracidad de la información', titleEn: '4. Accuracy of information', bodyEs: 'Garantizas que toda la información y los documentos que cargas son verídicos, propios y están vigentes. La información falsa o los documentos vencidos pueden suspender tu elegibilidad.', bodyEn: 'You warrant that all information and documents you upload are true, your own and current. False information or expired documents may suspend your eligibility.' },
    { titleEs: '5. Vehículo, licencia y seguros', titleEn: '5. Vehicle, license & insurance', bodyEs: 'Debes mantener tu licencia, seguro obligatorio y registro del vehículo vigentes, y conducir un vehículo en buen estado y debidamente asegurado conforme a la ley de Barbados.', bodyEn: "You must keep your driver's licence, compulsory insurance and vehicle registration current, and operate a roadworthy vehicle properly insured under the laws of Barbados." },
    { titleEs: '6. Normas de conducta y servicio', titleEn: '6. Conduct & service standards', bodyEs: 'Te comprometes a prestar un servicio seguro, puntual y respetuoso, a cumplir las normas de tránsito y a proteger la mercancía y los datos del destinatario.', bodyEn: 'You agree to provide safe, punctual and respectful service, to obey traffic laws, and to protect each shipment and the consignee’s data.' },
    { titleEs: '7. Pagos', titleEn: '7. Payments', bodyEs: 'Los pagos se liquidan por los fletes completados y se depositan en la cuenta bancaria a tu nombre. Las tarifas y condiciones pueden actualizarse y se notificarán en la app.', bodyEn: 'Payments are settled for completed freight and deposited to the bank account in your name. Rates and conditions may be updated and will be notified in the app.' },
    { titleEs: '8. Calificaciones y desactivación', titleEn: '8. Ratings & deactivation', bodyEs: 'Tu DriverScore se calcula con calificaciones y desempeño y afecta tu prioridad de asignación. PasarEx LM puede suspender o desactivar tu cuenta por incumplimiento de estos Términos.', bodyEn: 'Your DriverScore is computed from ratings and performance and affects your assignment priority. PasarEx LM may suspend or deactivate your account for breach of these Terms.' },
    { titleEs: '9. Protección de datos', titleEn: '9. Data protection', bodyEs: 'Autorizas el tratamiento de tus datos personales conforme a la Data Protection Act, 2019 de Barbados para operar el servicio, verificar tu elegibilidad y procesar pagos. Puedes acceder, actualizar y suprimir tus datos.', bodyEn: 'You authorize the processing of your personal data under the Barbados Data Protection Act, 2019 to operate the service, verify your eligibility and process payments. You may access, update and delete your data.' },
    { titleEs: '10. Modificaciones y ley aplicable', titleEn: '10. Modifications & governing law', bodyEs: 'PasarEx LM puede modificar estos Términos; el uso continuo implica aceptación. Estos Términos se rigen por las leyes de Barbados.', bodyEn: 'PasarEx LM may modify these Terms; continued use constitutes acceptance. These Terms are governed by the laws of Barbados.' },
  ],
  privacy: [
    { titleEs: '1. Quiénes somos', titleEn: '1. Who we are', bodyEs: 'PasarEx LM opera una plataforma de última milla en Barbados. Somos responsables del tratamiento de tus datos personales conforme a la Data Protection Act, 2019 de Barbados.', bodyEn: 'PasarEx LM operates a last-mile delivery platform in Barbados. We are the controller of your personal data under the Barbados Data Protection Act, 2019.' },
    { titleEs: '2. Datos que recopilamos', titleEn: '2. Data we collect', bodyEs: 'Datos de identidad y contacto (nombre, documento nacional, celular, correo, dirección), datos del vehículo, documentos y fotos que cargas (licencia, seguro, registro, identidad, factura de servicios, fotos del odómetro), ubicación GPS mientras estás en ruta, e información operativa (entregas, paquetes, millaje, calificaciones).', bodyEn: 'Identity and contact details (name, national ID, mobile, email, address), vehicle details, the documents and photos you upload (licence, insurance, registration, ID, utility bill, odometer photos), GPS location while you are on a route, and operational data (deliveries, packages, mileage, ratings).' },
    { titleEs: '3. Cómo usamos tus datos', titleEn: '3. How we use your data', bodyEs: 'Para verificar tu elegibilidad y antecedentes, asignarte fletes, coordinar y rastrear entregas, calcular tu pago y DriverScore, comunicarnos contigo (incluido WhatsApp) y cumplir obligaciones legales.', bodyEn: 'To verify your eligibility and background, assign you freight, coordinate and track deliveries, calculate your pay and DriverScore, communicate with you (including via WhatsApp), and meet legal obligations.' },
    { titleEs: '4. Ubicación', titleEn: '4. Location', bodyEs: 'Tu ubicación se comparte con Operaciones únicamente mientras tienes una ruta activa, para seguimiento de la entrega. Puedes desactivar el permiso de ubicación en tu dispositivo, pero esto puede impedir recibir o completar rutas.', bodyEn: 'Your location is shared with Ops only while you have an active route, for delivery tracking. You can turn off location permission on your device, but this may prevent you from receiving or completing routes.' },
    { titleEs: '5. Con quién compartimos', titleEn: '5. Who we share with', bodyEs: 'Con nuestro personal de Operaciones y seguridad, con proveedores que nos prestan servicios (mensajería WhatsApp, procesamiento OCR, alojamiento) bajo obligaciones de confidencialidad, y con autoridades cuando la ley lo exige. No vendemos tus datos.', bodyEn: 'With our Ops and security staff, with service providers who support us (WhatsApp messaging, OCR processing, hosting) under confidentiality obligations, and with authorities where required by law. We do not sell your data.' },
    { titleEs: '6. Conservación', titleEn: '6. Retention', bodyEs: 'Conservamos tus datos mientras tu cuenta esté activa y durante el periodo necesario para cumplir obligaciones legales, contables y de resolución de disputas; luego los eliminamos o anonimizamos.', bodyEn: 'We keep your data while your account is active and for as long as needed to meet legal, accounting and dispute-resolution obligations; after that we delete or anonymize it.' },
    { titleEs: '7. Tus derechos', titleEn: '7. Your rights', bodyEs: 'Bajo la Data Protection Act, 2019 puedes acceder, corregir, actualizar o solicitar la eliminación de tus datos, y oponerte a ciertos tratamientos. Puedes editar tu perfil en la app o contactarnos.', bodyEn: 'Under the Data Protection Act, 2019 you may access, correct, update or request deletion of your data, and object to certain processing. You can edit your profile in the app or contact us.' },
    { titleEs: '8. Seguridad', titleEn: '8. Security', bodyEs: 'Protegemos tus datos con controles de acceso por rol, cifrado en tránsito (HTTPS) y almacenamiento restringido. Ningún sistema es 100% seguro, pero trabajamos para protegerlos.', bodyEn: 'We protect your data with role-based access controls, encryption in transit (HTTPS) and restricted storage. No system is 100% secure, but we work to safeguard it.' },
    { titleEs: '9. Cambios y contacto', titleEn: '9. Changes & contact', bodyEs: 'Podemos actualizar esta política; publicaremos la nueva versión en la app. Para ejercer tus derechos o resolver dudas de privacidad, contáctanos por los canales de soporte de PasarEx.', bodyEn: 'We may update this policy; the new version will be posted in the app. To exercise your rights or raise privacy questions, contact us through PasarEx support channels.' },
  ],
};
