import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1781117643791 implements MigrationInterface {
    name = 'InitSchema1781117643791'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('driver', 'dispatcher', 'security_officer', 'admin', 'consignee')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying, "phone" character varying, "fullName" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'driver', "passwordHash" character varying, "refreshTokenHash" character varying, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `);
        await queryRunner.query(`CREATE TABLE "operating_areas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nameEs" character varying NOT NULL, "nameEn" character varying NOT NULL, "slug" character varying NOT NULL, "area" geometry(Polygon,4326), "centerLng" double precision, "centerLat" double precision, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_ed60a5003f05f32c211eaeb1f66" UNIQUE ("slug"), CONSTRAINT "PK_5e254ea91901b7126b0f4c5c0fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_087e1e3adf29e39d35b3dc0045" ON "operating_areas" USING GiST ("area") `);
        await queryRunner.query(`CREATE TYPE "public"."driver_profiles_status_enum" AS ENUM('idle', 'enroute', 'delivering', 'offduty')`);
        await queryRunner.query(`CREATE TYPE "public"."driver_profiles_tier_enum" AS ENUM('elite', 'preferente', 'estandar', 'nuevo')`);
        await queryRunner.query(`CREATE TABLE "driver_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cedula" character varying, "status" "public"."driver_profiles_status_enum" NOT NULL DEFAULT 'offduty', "onDuty" boolean NOT NULL DEFAULT false, "securityCleared" boolean NOT NULL DEFAULT false, "eligible" boolean NOT NULL DEFAULT false, "score" double precision NOT NULL DEFAULT '0', "tier" "public"."driver_profiles_tier_enum" NOT NULL DEFAULT 'nuevo', "deliveriesCount" integer NOT NULL DEFAULT '0', "acceptanceRate" double precision NOT NULL DEFAULT '100', "onTimeRate" double precision NOT NULL DEFAULT '100', "completionRate" double precision NOT NULL DEFAULT '100', "avgRating" double precision NOT NULL DEFAULT '0', "lastLng" double precision, "lastLat" double precision, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "REL_c22d0ffc4bff60e9a39c003759" UNIQUE ("userId"), CONSTRAINT "PK_6e002fc8a835351e070978fcad4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_type_enum" AS ENUM('moto', 'carro', 'van', 'camioneta', 'bici')`);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."vehicles_type_enum" NOT NULL, "plate" character varying NOT NULL, "brand" character varying, "model" character varying, "year" integer, "color" character varying, "capacityKg" double precision, "capacityVolM3" double precision, "dimensions" character varying, "refrigerated" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT true, "driverId" uuid, CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "availability_slots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "weekday" integer NOT NULL, "block" character varying NOT NULL, "driverId" uuid, CONSTRAINT "PK_70765e8e17c8f6374060d70589a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "approval_workflows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f326145fd927565de30b360264b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."approval_stages_mode_enum" AS ENUM('manual', 'automatic')`);
        await queryRunner.query(`CREATE TYPE "public"."approval_stages_responsiblerole_enum" AS ENUM('driver', 'dispatcher', 'security_officer', 'admin', 'consignee')`);
        await queryRunner.query(`CREATE TABLE "approval_stages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nameEs" character varying NOT NULL, "nameEn" character varying NOT NULL, "sortOrder" integer NOT NULL, "mode" "public"."approval_stages_mode_enum" NOT NULL DEFAULT 'manual', "responsibleRole" "public"."approval_stages_responsiblerole_enum" NOT NULL DEFAULT 'dispatcher', "isSecurityClearance" boolean NOT NULL DEFAULT false, "requiredDocs" jsonb NOT NULL DEFAULT '[]', "ruleset" jsonb, "slaHours" integer NOT NULL DEFAULT '24', "workflowId" uuid, CONSTRAINT "PK_24f1b0f60ba0f253c6b884edc22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."applications_status_enum" AS ENUM('draft', 'in_review', 'approved', 'rejected', 'returned')`);
        await queryRunner.query(`CREATE TYPE "public"."applications_vehicletype_enum" AS ENUM('moto', 'carro', 'van', 'camioneta', 'bici')`);
        await queryRunner.query(`CREATE TABLE "applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" character varying NOT NULL, "status" "public"."applications_status_enum" NOT NULL DEFAULT 'draft', "draft" jsonb NOT NULL DEFAULT '{}', "applicantName" character varying, "vehicleType" "public"."applications_vehicletype_enum", "plate" character varying, "zones" jsonb NOT NULL DEFAULT '[]', "securityChecks" jsonb NOT NULL DEFAULT '{}', "score" double precision, "submittedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "driverId" uuid, "workflowId" uuid, "currentStageId" uuid, CONSTRAINT "UQ_8e384653e7bcce736b99c9feea4" UNIQUE ("reference"), CONSTRAINT "PK_938c0a27255637bde919591888f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."approval_tasks_status_enum" AS ENUM('pending', 'passed', 'failed', 'returned')`);
        await queryRunner.query(`CREATE TABLE "approval_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."approval_tasks_status_enum" NOT NULL DEFAULT 'pending', "decidedByUserId" character varying, "decidedByName" character varying, "reason" text, "decidedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "applicationId" uuid, "stageId" uuid, CONSTRAINT "PK_612540cffe174929e1ff58c893b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."freights_requiredvehicle_enum" AS ENUM('moto', 'carro', 'van', 'camioneta', 'bici')`);
        await queryRunner.query(`CREATE TYPE "public"."freights_status_enum" AS ENUM('draft', 'available', 'broadcasting', 'assigned', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "freights" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" character varying NOT NULL, "client" character varying NOT NULL, "consigneeName" character varying, "consigneePhone" character varying, "pickupZone" character varying NOT NULL, "dropZone" character varying NOT NULL, "pickupPoint" geometry(Point,4326), "dropPoint" geometry(Point,4326), "requiredVehicle" "public"."freights_requiredvehicle_enum" NOT NULL, "weightKg" double precision NOT NULL DEFAULT '0', "windowMinutes" integer, "distanceKm" double precision, "payout" integer NOT NULL DEFAULT '0', "priority" boolean NOT NULL DEFAULT false, "status" "public"."freights_status_enum" NOT NULL DEFAULT 'available', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "assignedDriverId" uuid, CONSTRAINT "UQ_5ab43ee34ea167c4340283292db" UNIQUE ("reference"), CONSTRAINT "PK_1962972423b23c02a3a0e8c2265" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4fd1781d34aa1be0d4df576249" ON "freights" USING GiST ("pickupPoint") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a8e2b6b188c9c773b77acb0d3" ON "freights" USING GiST ("dropPoint") `);
        await queryRunner.query(`CREATE TABLE "tenders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "currentWave" integer NOT NULL DEFAULT '0', "rankedDriverIds" jsonb NOT NULL DEFAULT '[]', "open" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "freightId" uuid, CONSTRAINT "PK_13fdd4229818a97b5102199463b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tender_responses_response_enum" AS ENUM('accept', 'decline', 'expire')`);
        await queryRunner.query(`CREATE TABLE "tender_responses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "wave" integer NOT NULL, "response" "public"."tender_responses_response_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "tenderId" uuid, "driverId" uuid, CONSTRAINT "PK_2fd9eeea06be97bc915226a09bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."deliveries_status_enum" AS ENUM('assigned', 'en_route_pickup', 'picked_up', 'en_route', 'delivered', 'failed')`);
        await queryRunner.query(`CREATE TABLE "deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."deliveries_status_enum" NOT NULL DEFAULT 'assigned', "timeline" jsonb NOT NULL DEFAULT '{}', "trackingToken" character varying NOT NULL, "etaMinutes" integer, "completedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "freightId" uuid, "driverId" uuid, CONSTRAINT "UQ_21e041a85fbb9061198b9f3c37a" UNIQUE ("trackingToken"), CONSTRAINT "PK_a6ef225c5c5f0974e503bfb731f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "location_pings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driverId" character varying NOT NULL, "deliveryId" character varying, "lng" double precision NOT NULL, "lat" double precision NOT NULL, "heading" double precision, "speed" double precision, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b666c5c0408c8bd318811640532" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7e522fe8e0ac54aac32483f25a" ON "location_pings" ("driverId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "ratings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stars" integer NOT NULL, "feedback" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deliveryId" uuid, "driverId" uuid, CONSTRAINT "PK_0f31425b073219379545ad68ed9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."document_types_appliesto_enum" AS ENUM('driver', 'vehicle')`);
        await queryRunner.query(`CREATE TABLE "document_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "nameEs" character varying NOT NULL, "nameEn" character varying NOT NULL, "appliesTo" "public"."document_types_appliesto_enum" NOT NULL DEFAULT 'driver', "required" boolean NOT NULL DEFAULT true, "tracksExpiry" boolean NOT NULL DEFAULT false, "acceptedFileTypes" jsonb NOT NULL DEFAULT '["application/pdf","image/jpeg","image/png"]', "validationRules" jsonb, "reminderOffsets" jsonb NOT NULL DEFAULT '[30,15,3]', "sortOrder" integer NOT NULL DEFAULT '0', "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_371a372bde705d8bd4963024153" UNIQUE ("key"), CONSTRAINT "PK_d467d7eeb7c8ce216e90e8494aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."documents_status_enum" AS ENUM('pending', 'approved', 'rejected', 'expired')`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fileRef" character varying, "issueDate" date, "expiryDate" date, "status" "public"."documents_status_enum" NOT NULL DEFAULT 'pending', "rejectionReason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "documentTypeId" uuid, "driverId" uuid, CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scoring_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL DEFAULT 'default', "active" boolean NOT NULL DEFAULT true, "weights" jsonb NOT NULL, "tiers" jsonb NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8a39cb68d00a05c8f3b1498a04c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_templates_channel_enum" AS ENUM('push', 'whatsapp', 'sms', 'in_app')`);
        await queryRunner.query(`CREATE TABLE "notification_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "channel" "public"."notification_templates_channel_enum" NOT NULL, "locale" character varying(2) NOT NULL, "subject" character varying, "body" text NOT NULL, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_76f0fc48b8d057d2ae7f3a2848a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bf995f7c8765fc0007919df251" ON "notification_templates" ("key", "channel", "locale") `);
        await queryRunner.query(`CREATE TABLE "reminders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "templateKey" character varying NOT NULL, "scheduledFor" TIMESTAMP WITH TIME ZONE NOT NULL, "offsetDays" integer NOT NULL, "sent" boolean NOT NULL DEFAULT false, "sentAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "documentId" uuid, CONSTRAINT "PK_38715fec7f634b72c6cf7ea4893" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('push', 'whatsapp', 'sms', 'in_app')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipientUserId" character varying, "recipientContact" character varying, "channel" "public"."notifications_channel_enum" NOT NULL, "templateKey" character varying NOT NULL, "subject" character varying, "renderedBody" text NOT NULL, "status" character varying NOT NULL DEFAULT 'sent', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actorUserId" character varying, "actorName" character varying, "action" character varying NOT NULL, "entity" character varying NOT NULL, "entityId" character varying, "before" jsonb, "after" jsonb, "reason" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2643f2a68c662985433dbddca1" ON "audit_logs" ("entity", "entityId") `);
        await queryRunner.query(`CREATE TABLE "driver_operating_areas" ("driverProfilesId" uuid NOT NULL, "operatingAreasId" uuid NOT NULL, CONSTRAINT "PK_d952c0d53643adc890e1b0953e3" PRIMARY KEY ("driverProfilesId", "operatingAreasId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9be5dee96ae8c698fce4bcdd4" ON "driver_operating_areas" ("driverProfilesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_45531423775e22c97e204467c4" ON "driver_operating_areas" ("operatingAreasId") `);
        await queryRunner.query(`ALTER TABLE "driver_profiles" ADD CONSTRAINT "FK_c22d0ffc4bff60e9a39c0037590" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_28d7607488252336b22511e9e80" FOREIGN KEY ("driverId") REFERENCES "driver_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_slots" ADD CONSTRAINT "FK_22de830a452d96c57cc09dd08aa" FOREIGN KEY ("driverId") REFERENCES "driver_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_stages" ADD CONSTRAINT "FK_cd095ca69f808d2eaf040b4cbc3" FOREIGN KEY ("workflowId") REFERENCES "approval_workflows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_bbccc3c314e4ef0b89007e89f52" FOREIGN KEY ("driverId") REFERENCES "driver_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_de962aa1d38ed437d291c895013" FOREIGN KEY ("workflowId") REFERENCES "approval_workflows"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_e714148316e073e387ea549a976" FOREIGN KEY ("currentStageId") REFERENCES "approval_stages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_tasks" ADD CONSTRAINT "FK_f7d4ff8c81c588a69090c0d21d5" FOREIGN KEY ("applicationId") REFERENCES "applications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_tasks" ADD CONSTRAINT "FK_e92dcc6e591a93faf961b2648b7" FOREIGN KEY ("stageId") REFERENCES "approval_stages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "freights" ADD CONSTRAINT "FK_48b6d829bc1822b6daad0a47c58" FOREIGN KEY ("assignedDriverId") REFERENCES "driver_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenders" ADD CONSTRAINT "FK_15bf6b747f2c423c4cb6171cd28" FOREIGN KEY ("freightId") REFERENCES "freights"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tender_responses" ADD CONSTRAINT "FK_49f67a0c1b3872570ab313874c6" FOREIGN KEY ("tenderId") REFERENCES "tenders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tender_responses" ADD CONSTRAINT "FK_bcfb5ec0a0b6e4b69d354ad69b1" FOREIGN KEY ("driverId") REFERENCES "driver_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD CONSTRAINT "FK_d7008cc2d1d898e6be9bde7f86e" FOREIGN KEY ("freightId") REFERENCES "freights"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD CONSTRAINT "FK_a6cc84e1c957ed2d25bd7eda4ba" FOREIGN KEY ("driverId") REFERENCES "driver_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_63b06dd5d2826ba640060229b5e" FOREIGN KEY ("deliveryId") REFERENCES "deliveries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_c94a1b5503ed744bb24587c2766" FOREIGN KEY ("driverId") REFERENCES "driver_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_6c6b9775baa0c8973bd829a8e46" FOREIGN KEY ("documentTypeId") REFERENCES "document_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_42c2883cc4f370d5699bf805cb9" FOREIGN KEY ("driverId") REFERENCES "driver_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD CONSTRAINT "FK_7b9b1ff9aba560af0928a419b77" FOREIGN KEY ("documentId") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driver_operating_areas" ADD CONSTRAINT "FK_e9be5dee96ae8c698fce4bcdd4c" FOREIGN KEY ("driverProfilesId") REFERENCES "driver_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "driver_operating_areas" ADD CONSTRAINT "FK_45531423775e22c97e204467c42" FOREIGN KEY ("operatingAreasId") REFERENCES "operating_areas"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "driver_operating_areas" DROP CONSTRAINT "FK_45531423775e22c97e204467c42"`);
        await queryRunner.query(`ALTER TABLE "driver_operating_areas" DROP CONSTRAINT "FK_e9be5dee96ae8c698fce4bcdd4c"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP CONSTRAINT "FK_7b9b1ff9aba560af0928a419b77"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_42c2883cc4f370d5699bf805cb9"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_6c6b9775baa0c8973bd829a8e46"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_c94a1b5503ed744bb24587c2766"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_63b06dd5d2826ba640060229b5e"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP CONSTRAINT "FK_a6cc84e1c957ed2d25bd7eda4ba"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP CONSTRAINT "FK_d7008cc2d1d898e6be9bde7f86e"`);
        await queryRunner.query(`ALTER TABLE "tender_responses" DROP CONSTRAINT "FK_bcfb5ec0a0b6e4b69d354ad69b1"`);
        await queryRunner.query(`ALTER TABLE "tender_responses" DROP CONSTRAINT "FK_49f67a0c1b3872570ab313874c6"`);
        await queryRunner.query(`ALTER TABLE "tenders" DROP CONSTRAINT "FK_15bf6b747f2c423c4cb6171cd28"`);
        await queryRunner.query(`ALTER TABLE "freights" DROP CONSTRAINT "FK_48b6d829bc1822b6daad0a47c58"`);
        await queryRunner.query(`ALTER TABLE "approval_tasks" DROP CONSTRAINT "FK_e92dcc6e591a93faf961b2648b7"`);
        await queryRunner.query(`ALTER TABLE "approval_tasks" DROP CONSTRAINT "FK_f7d4ff8c81c588a69090c0d21d5"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_e714148316e073e387ea549a976"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_de962aa1d38ed437d291c895013"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_bbccc3c314e4ef0b89007e89f52"`);
        await queryRunner.query(`ALTER TABLE "approval_stages" DROP CONSTRAINT "FK_cd095ca69f808d2eaf040b4cbc3"`);
        await queryRunner.query(`ALTER TABLE "availability_slots" DROP CONSTRAINT "FK_22de830a452d96c57cc09dd08aa"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_28d7607488252336b22511e9e80"`);
        await queryRunner.query(`ALTER TABLE "driver_profiles" DROP CONSTRAINT "FK_c22d0ffc4bff60e9a39c0037590"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45531423775e22c97e204467c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9be5dee96ae8c698fce4bcdd4"`);
        await queryRunner.query(`DROP TABLE "driver_operating_areas"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2643f2a68c662985433dbddca1"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TABLE "reminders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf995f7c8765fc0007919df251"`);
        await queryRunner.query(`DROP TABLE "notification_templates"`);
        await queryRunner.query(`DROP TYPE "public"."notification_templates_channel_enum"`);
        await queryRunner.query(`DROP TABLE "scoring_configs"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TYPE "public"."documents_status_enum"`);
        await queryRunner.query(`DROP TABLE "document_types"`);
        await queryRunner.query(`DROP TYPE "public"."document_types_appliesto_enum"`);
        await queryRunner.query(`DROP TABLE "ratings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e522fe8e0ac54aac32483f25a"`);
        await queryRunner.query(`DROP TABLE "location_pings"`);
        await queryRunner.query(`DROP TABLE "deliveries"`);
        await queryRunner.query(`DROP TYPE "public"."deliveries_status_enum"`);
        await queryRunner.query(`DROP TABLE "tender_responses"`);
        await queryRunner.query(`DROP TYPE "public"."tender_responses_response_enum"`);
        await queryRunner.query(`DROP TABLE "tenders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a8e2b6b188c9c773b77acb0d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4fd1781d34aa1be0d4df576249"`);
        await queryRunner.query(`DROP TABLE "freights"`);
        await queryRunner.query(`DROP TYPE "public"."freights_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."freights_requiredvehicle_enum"`);
        await queryRunner.query(`DROP TABLE "approval_tasks"`);
        await queryRunner.query(`DROP TYPE "public"."approval_tasks_status_enum"`);
        await queryRunner.query(`DROP TABLE "applications"`);
        await queryRunner.query(`DROP TYPE "public"."applications_vehicletype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."applications_status_enum"`);
        await queryRunner.query(`DROP TABLE "approval_stages"`);
        await queryRunner.query(`DROP TYPE "public"."approval_stages_responsiblerole_enum"`);
        await queryRunner.query(`DROP TYPE "public"."approval_stages_mode_enum"`);
        await queryRunner.query(`DROP TABLE "approval_workflows"`);
        await queryRunner.query(`DROP TABLE "availability_slots"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_type_enum"`);
        await queryRunner.query(`DROP TABLE "driver_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."driver_profiles_tier_enum"`);
        await queryRunner.query(`DROP TYPE "public"."driver_profiles_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_087e1e3adf29e39d35b3dc0045"`);
        await queryRunner.query(`DROP TABLE "operating_areas"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
